Validator V2 Updates - v2.03 (#248)
* prettier format

* initial updates for validatorV2

* Add 102.1.1

* 1.1.1 rule added

* fix location of 102.1.1

* 1.1.3 reporting-org to iati-identifier check

* 1.1.21 identifiers rule added

* 12.3.1 sector % range

* 2.1.2 sector percentage sums

* 6.14.1 and 6.13.1 policy-marker attribute rules

* 6.2.2 sector requirement

* 6.7.2 sector

* 6.6.2 rule

* 7.8.1 rule added for currency

* 107.1.1 default-aid-type

* 12.1.1 recipient-region/country range

* 12.2.1 capital-spend and budget-item range

* 3.1.2 recipient-country percentage

* 3.4.2 recipient-region/country percentage sum

* organisation identifier prefix checks against ORG-ID

* 7.5.3 budget period

* 7.5.2 value-date check

* 8.X.3 result indicator value omission

* 8.6.3 period date_order

* 1.X.1 no spaces or newlines rules

* 1.X.13 regex_matches no special characters

* adding ruleInfo to many existing rules

* result indicator value number type check

* 7.9.1 7.9.2 7.9.4 country budget item percentages

* 107.1.2 default aid type limit

* 107.2.1 complete

* 107.2.2 complete

* 2.1.1 sector percentage requirements

* 2.1.4 sector vocab percentage requirements

* refactor to use or inside [] for some xpaths

* 4.3.1 4.4.1 title and description narrative checks

* 3.6.2, 3.7.1, 3.7.2 recipient location rules

* 3.4.1 complete

* 3.1.4 3.4.4 added, various small fixes

* 3.1.1 added

* add  @vocabulary = '' as option

* more specific name

* add 7.8.2 currency check

* remove 1.X.8 and 1.X.13 rules that aren't in V1

* add idConditions to identifier checks

* 3.4.2 add recipient-country into condition

* remove 1yr budget limit for planned-disbursement 7.5.3, added in error

* add paths to if_then rules for additional context generation in the output

* fix message for 3.4.1

* fix incorrectly placed rules in JSON

* schema updates and push to redis workflow

* add JS implementation specifications

* remove 7.5.2 as it duplicates Schema check

* add job to trigger csv update on rule tracker repo

* fix spelling errors with identifier

* remove duplicative rule 1.1.1 and update message for 1.1.21

* fix 107.2.2 by moving to transaction level evaluation

* add commit sha to redis cache

* use file commit sha instead of current commit sha

* try different format

* add -- separator for filepath

* add fetch-depth

* add support for guidance links

* push rulesets to PROD redis-cacher

* updates for validator v2

* remove reference to Readme.md

* link and workflow information added

* additional updates

* add missing guidance links

* 107.1.2 adding guidance link

* apply 4.3.1 and 4.4.1 to all title and description narratives like V1

* use specific paths to increase performance where possible

* Simplify rules text generation

* Rule links

* Lint

* Multiple possible locations to pull path from

* Lint

* Sort like version numbers

* 2.1.2 only evaluate sum if more than one sector element is present per vocabulary

* comment out PRD redis update while merging into version-2.03 branch

Co-authored-by: akmiller01 <alex.k.miller@gmail.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,10 +3,19 @@
 
 name: CI_version-2.03
 
+env:
+  DEV_DEFAULT_KEY: ${{ secrets.DEV_CACHER_DEFAULT_KEY }} # Azure Functions default API Key for Redis-cacher
+  PROD_DEFAULT_KEY: ${{ secrets.PROD_CACHER_DEFAULT_KEY }} # Azure Functions default API Key for Redis-cacher
+  VERSION: 2.03
+
 on:
   push:
-    branches: [version-2.03]
+    paths-ignore: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
+      - "**/*.rst"
+    branches: [version-2.03, v2.03/validatorV2]
   pull_request:
+    paths-ignore:
+      - "**/*.rst"
     branches: [version-2.03]
 
 jobs:
@@ -48,3 +57,71 @@ jobs:
         run: |
           python -m jsonschema -i rulesets/standard.json schema.json
           ./meta_tests.sh python testrules.py
+
+  cache-ruleset-dev:
+    needs: build
+    runs-on: ubuntu-latest
+    if: ${{ github.event_name == 'push' }} # only push to the redis cache on PUSH
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          # Number of commits to fetch. 0 indicates all history for all branches and tags.
+          fetch-depth: 0
+
+      - name: POST ruleset/standard.json to func-iati-redis-cacher-dev
+        run: |
+          FILE_COMMIT_SHA=$(git log -1 --format='%H' -- './rulesets/standard.json')
+          echo $FILE_COMMIT_SHA
+          HTTP_CODE=$(curl --write-out "%{http_code}\n" \
+          --location --request POST 'https://func-iati-redis-cacher-dev.azurewebsites.net/api/pvt/cache?key=ruleset'$VERSION'&commitsha='$FILE_COMMIT_SHA \
+          --header 'x-functions-key: '$DEV_DEFAULT_KEY \
+          --header 'Content-Type: application/json' \
+          --data-binary '@./rulesets/standard.json' \
+          --output curl_out.txt \
+          --silent )
+          echo $HTTP_CODE
+          if [[ $HTTP_CODE != '200' ]] ; then
+            echo "Reponse is not 200 from func-iati-redis-cacher-dev, check error logs"
+            cat curl_out.txt
+            exit 1
+          fi
+
+  # cache-ruleset-prod:
+  #   needs: cache-ruleset-dev
+  #   runs-on: ubuntu-latest
+  #   if: ${{ github.event_name == 'push' }} # only push to the redis cache on PUSH
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #       with:
+  #         # Number of commits to fetch. 0 indicates all history for all branches and tags.
+  #         fetch-depth: 0
+
+  #     - name: POST ruleset/standard.json to func-iati-redis-cacher-PROD
+  #       run: |
+  #         FILE_COMMIT_SHA=$(git log -1 --format='%H' -- './rulesets/standard.json')
+  #         echo $FILE_COMMIT_SHA
+  #         HTTP_CODE=$(curl --write-out "%{http_code}\n" \
+  #         --location --request POST 'https://func-iati-redis-cacher-prod.azurewebsites.net/api/pvt/cache?key=ruleset'$VERSION'&commitsha='$FILE_COMMIT_SHA \
+  #         --header 'x-functions-key: '$PROD_DEFAULT_KEY \
+  #         --header 'Content-Type: application/json' \
+  #         --data-binary '@./rulesets/standard.json' \
+  #         --output curl_out.txt \
+  #         --silent )
+  #         echo $HTTP_CODE
+  #         if [[ $HTTP_CODE != '200' ]] ; then
+  #           echo "Reponse is not 200 from func-iati-redis-cacher-PROD, check error logs"
+  #           cat curl_out.txt
+  #           exit 1
+  #         fi
+
+  update-rule-tracker:
+    needs: build
+    runs-on: ubuntu-latest
+    if: ${{ github.event_name == 'push' }} # only push to the rule tracker on PUSH
+    steps:
+      - name: "Trigger update of rule tracker repo .csv"
+        run: |
+          curl -X POST https://api.github.com/repos/IATI/validator-rule-tracker/dispatches \
+          -H 'Accept: application/vnd.github.everest-preview+json' \
+          -u ${{ secrets.NJO_PAT }} \
+          --data '{"event_type": "update", "client_payload": { "resourceName": "rulesets", "repo": "'"$GITHUB_REPOSITORY"'", "sha": "'"$GITHUB_SHA"'"}}'
