push rulesets to PROD redis-cacher

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,6 +5,7 @@ name: CI_version-2.03
 
 env:
   DEV_DEFAULT_KEY: ${{ secrets.DEV_CACHER_DEFAULT_KEY }} # Azure Functions default API Key for Redis-cacher
+  PROD_DEFAULT_KEY: ${{ secrets.PROD_CACHER_DEFAULT_KEY }} # Azure Functions default API Key for Redis-cacher
   VERSION: 2.03
 
 on:
@@ -59,7 +60,7 @@ jobs:
           python -m jsonschema -i rulesets/standard.json schema.json
           ./meta_tests.sh python testrules.py
 
-  cache-ruleset:
+  cache-ruleset-dev:
     needs: build
     runs-on: ubuntu-latest
     if: ${{ github.event_name == 'push' }} # only push to the redis cache on PUSH
@@ -69,7 +70,7 @@ jobs:
           # Number of commits to fetch. 0 indicates all history for all branches and tags.
           fetch-depth: 0
 
-      - name: POST ruleset/standard.json to redis-cacher
+      - name: POST ruleset/standard.json to func-iati-redis-cacher-dev
         run: |
           FILE_COMMIT_SHA=$(git log -1 --format='%H' -- './rulesets/standard.json')
           echo $FILE_COMMIT_SHA
@@ -82,7 +83,35 @@ jobs:
           --silent )
           echo $HTTP_CODE
           if [[ $HTTP_CODE != '200' ]] ; then
-            echo "Reponse is not 200 from redis-cacher, check error logs"
+            echo "Reponse is not 200 from func-iati-redis-cacher-dev, check error logs"
+            cat curl_out.txt
+            exit 1
+          fi
+
+  cache-ruleset-prod:
+    needs: cache-ruleset-dev
+    runs-on: ubuntu-latest
+    if: ${{ github.event_name == 'push' }} # only push to the redis cache on PUSH
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          # Number of commits to fetch. 0 indicates all history for all branches and tags.
+          fetch-depth: 0
+
+      - name: POST ruleset/standard.json to func-iati-redis-cacher-PROD
+        run: |
+          FILE_COMMIT_SHA=$(git log -1 --format='%H' -- './rulesets/standard.json')
+          echo $FILE_COMMIT_SHA
+          HTTP_CODE=$(curl --write-out "%{http_code}\n" \
+          --location --request POST 'https://func-iati-redis-cacher-prod.azurewebsites.net/api/pvt/cache?key=ruleset'$VERSION'&commitsha='$FILE_COMMIT_SHA \
+          --header 'x-functions-key: '$PROD_DEFAULT_KEY \
+          --header 'Content-Type: application/json' \
+          --data-binary '@./rulesets/standard.json' \
+          --output curl_out.txt \
+          --silent )
+          echo $HTTP_CODE
+          if [[ $HTTP_CODE != '200' ]] ; then
+            echo "Reponse is not 200 from func-iati-redis-cacher-PROD, check error logs"
             cat curl_out.txt
             exit 1
           fi
